apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "istiodemo.fullname" . }}canary
  labels:
    app: {{ template "istiodemo.name" . }}
    canary: "true"
    chart: {{ template "istiodemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.canaryDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "istiodemo.name" . }}
      canary: "true"
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.jaegertracing.io/inject: "true"
      labels:
        app: {{ template "istiodemo.name" . }}
        canary: "true"
        release: {{ .Release.Name }}
        version: {{.Values.version}}
    spec:
      serviceAccountName: {{ include "istiodemo.serviceAccountName" . }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}canary
          image: "{{ .Values.canaryDeployment.image.repository }}:{{ .Values.canaryDeployment.image.tag }}"
          imagePullPolicy: {{ .Values.canaryDeployment.image.pullPolicy }}
          env:          
          {{- range $key, $val := .Values.canaryDeployment.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end}}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{.Values.service.port}}
          readinessProbe:
            tcpSocket:
              port: {{.Values.service.port}}
