apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiodemo-destination-rule
  labels:
    chart: {{ template "istiodemo.chart" . }}
    release: {{ .Release.Name }}
spec:
  host: {{ .Values.service.name }}.{{.Release.Namespace}}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: current
    labels:
      canary: "false"
  - name: canary
    labels:
      canary: "true"
