apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.Release.Name}}
  labels:
    chart: {{template "istiodemo.chart" .}}
    release: {{.Release.Name}}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-web
        protocol: HTTP
      hosts:
        - {{.Values.service.host}}
