apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istiodemo-virtual-service
  labels:
    chart: {{ template "istiodemo.chart" . }}
    release: {{ .Release.Name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Release.Name}}
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: current
        port:
          number: {{ .Values.service.port }}
      weight: {{ .Values.currentDeployment.weight }}
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: canary
        port:
          number: {{ .Values.service.port }}
      weight: {{ .Values.canaryDeployment.weight }}
      
